"""empty message

Revision ID: 2c66958fba1d
Revises: 1fc543434118
Create Date: 2023-11-05 17:15:26.088874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c66958fba1d'
down_revision = '1fc543434118'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('autor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apellidos', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('edad', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('pais', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('descripcion', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('autor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('email')
        batch_op.drop_column('descripcion')
        batch_op.drop_column('pais')
        batch_op.drop_column('edad')
        batch_op.drop_column('apellidos')

    # ### end Alembic commands ###
